/*
 * File: app/model/IncomeGeneralModel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.IncomeGeneralModel', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'trunk_owner'
        },
        {
            name: 'country_name'
        },
        {
            name: 'country_code'
        },
        {
            name: 'operator_prefix',
            sortType: 'asInt',
            type: 'int'
        },
        {
            name: 'call_duration',
            sortType: 'asFloat',
            type: 'asFloat'
        },
        {
            name: 'acd',
            sortType: 'asFloat',
            type: 'float'
        },
        {
            name: 'asr',
            sortType: 'asFloat',
            type: 'float'
        },
        {
            name: 'calls',
            sortType: 'asInt',
            type: 'int'
        }
    ]
});