/*
 * File: app/model/MyModel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.MyModel', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'country_name',
            mapping: 'country_name'
        },
        {
            name: 'country_code',
            sortType: 'asInt',
            type: 'int'
        },
//        {
//            name: 'country_desc'
//        },
        {
            name: 'operator_prefix',
            sortType: 'asInt',
            type: 'int'
        },
        {
            name: 'call_duration_h',
            sortType: 'asInt',
            type: 'float'
        },
        {
            name: 'call_duration_m',
            sortType: 'asInt',
            type: 'float'
        },
        {
            name: 'priority',
            sortType: 'asInt',
            type: 'int'
        },
        {
            name: 'acd_h',
            sortType: 'asInt',
            type: 'float'
        },
        {
            name: 'acd_m',
            sortType: 'asInt',
            type: 'float'
        },
        {
            name: 'asr_h',
            sortType: 'asInt',
            type: 'float'
        },
        {
            name: 'asr_m',
            sortType: 'asInt',
            type: 'float'
        },
        {
            name: 'calls_h',
            sortType: 'asInt',
            type: 'float'
        },
        {
            name: 'calls_m',
            sortType: 'asInt',
            type: 'float'
        },
//        {
//            name: 'check',
//            sortType: 'asInt',
//            type: 'float'
//        }
    ]
});